version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: napominalka-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TIMEZONE=${TIMEZONE:-UTC}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    env_file:
      - .env
    volumes:
      # Монтируем логи (опционально)
      - ./logs:/app/logs
    networks:
      - bot-network
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    # Политика перезапуска
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge

# Опционально: добавить Redis для хранения данных
# redis:
#   image: redis:7-alpine
#   container_name: napominalka-redis
#   restart: unless-stopped
#   volumes:
#     - redis_data:/data
#   networks:
#     - bot-network

# volumes:
#   redis_data:
