version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: reminder-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/app/data/reminders.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
